Repository gardener/docforge, pull requests merged in 2020-11, with the labels that each got.

#82 fix wrong handling of markdown links with src= or href= in URL
  pkg/reactor/content_processor.go
  pkg/reactor/content_processor_test.go
Labels: component/documentation, needs/ok-to-test, needs/review, size/m

#85 fix md link text and destination updates
  pkg/markdown/links.go
  pkg/markdown/links_test.go
  pkg/markdown/parser/links.go
Labels: component/documentation, needs/ok-to-test, needs/review, size/m

#80 GitHub templates update
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/pull_request_template.md
Labels: needs/ok-to-test, needs/review, size/xs

#91 support for GitHub commit(s) resource links
  pkg/resourcehandlers/github/resource_locator.go
  pkg/resourcehandlers/github/resource_locator_test.go
Labels: component/documentation, needs/ok-to-test, size/xs

#77 Generate cmd reference docs on release
  .ci/docs-gen
  .ci/pipeline_definitions
  Makefile
Labels: component/documentation, needs/ok-to-test, size/s

#79 Manifests as Go templates
  cmd/app/cmd.go
  cmd/app/config.go
Labels: component/documentation, kind/enhancement, needs/ok-to-test, size/s

#89 fix silent download fail for incorrect url
  pkg/reactor/document_worker.go
  pkg/reactor/download_controller.go
  pkg/resourcehandlers/github/github_resource_handler.go
  pkg/resourcehandlers/resource_handlers.go
Labels: component/documentation, needs/ok-to-test, reviewed/lgtm, size/xs

#87 add support for including modules
  go.mod
  go.sum
  pkg/api/validate.go
  pkg/reactor/content_processor_test.go
  pkg/reactor/reactor.go
  pkg/reactor/reactor_test.go
  pkg/resourcehandlers/fs/fs.go
  pkg/resourcehandlers/fs/fs_test.go
  pkg/resourcehandlers/github/github_resource_handler.go
  pkg/resourcehandlers/github/github_resource_handler_test.go
  pkg/resourcehandlers/github/integration_test.go
  pkg/resourcehandlers/resource_handlers.go
  pkg/resourcehandlers/resource_handlers_test.go
Labels: kind/api-change, needs/changes, needs/ok-to-test, reviewed/ok-to-test, size/l

#93 cicd gen-docs
  .ci/docs-gen
  .ci/pipeline_definitions
  VERSION
Labels: needs/review, size/xs

#104 Silence command usage on errors except those that require it for reference
  cmd/app/cmd.go
Labels: component/documentation, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#102 Common html link parser
  pkg/hugo/processor.go
  pkg/markdown/html_links.go
  pkg/markdown/links.go
  pkg/markdown/links_test.go
  pkg/markdown/parser/document.go
  pkg/markdown/parser/links_test.go
  pkg/markdown/parser/types.go
  pkg/reactor/content_processor.go
Labels: component/documentation, needs/ok-to-test, reviewed/ok-to-test, size/m

#107 improve the help for cli ref md
  cmd/app/completion.go
Labels: kind/enhancement, needs/review, size/xs

#110 fix false multiple peer nodes with property index error
  pkg/hugo/fswriter.go
Labels: area/documentation, needs/ok-to-test, size/xs

#115 Do not panic when all git commits are internal
  pkg/reactor/gitinfo_controller.go
  pkg/resourcehandlers/fs/fs.go
  pkg/resourcehandlers/github/github_resource_handler.go
  pkg/resourcehandlers/github/gitinfo.go
Labels: needs/ok-to-test, reviewed/ok-to-test, size/xs

#99 Manifest documentation
  README.md
  docs/index.md
  docs/manifest-ref.md
  docs/manifests.md
  docs/user-index.md
  pkg/api/types.go
Labels: area/documentation, component/documentation, kind/api-change, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, priority/critical, size/xl

#117 prevent reduntant frontmatter property: "title"
  .ci/build
  pkg/processors/frontmatter.go
  pkg/processors/frontmatter_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#119 Fix document not updated after HTML links update
  pkg/reactor/content_processor.go
Labels: component/documentation, needs/ok-to-test, needs/review, size/xs

#122 Fix concurrent map writes
  pkg/reactor/gitinfo_controller.go
Labels: needs/ok-to-test, needs/review, size/xs

#120 Read manifest from GitHub url or the file system
  cmd/app/cmd.go
  cmd/app/config.go
  cmd/app/manifest.go
  pkg/resourcehandlers/github/github_resource_handler.go
Labels: component/documentation, needs/ok-to-test, needs/review, reviewed/ok-to-test, size/m

#124 Fix deferred unlock miss
  pkg/reactor/build.go
  pkg/reactor/gitinfo_controller.go
Labels: needs/ok-to-test, priority/critical, reviewed/lgtm, reviewed/ok-to-test, size/xs

#127 add more context to download logs/errs
  cmd/app/cmd.go
  pkg/jobs/jobs.go
  pkg/jobs/jobs_test.go
  pkg/reactor/content_processor.go
  pkg/reactor/content_processor_test.go
  pkg/reactor/download_controller.go
Labels: needs/ok-to-test, size/m

#129 add http log
  cmd/app/factory.go
Labels: needs/ok-to-test, size/xs

#131 add sanity check for links
  pkg/hugo/processor.go
  pkg/markdown/html_links.go
  pkg/reactor/content_processor.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#135 Use alpine docker image from gcr.io registry
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#134 Fixes uses of version segment in github urls
  pkg/resourcehandlers/github/github_resource_handler.go
  pkg/resourcehandlers/github/github_resource_handler_test.go
  pkg/resourcehandlers/github/resource_locator.go
Labels: needs/ok-to-test, reviewed/lgtm, reviewed/ok-to-test, size/m
