Repository gardener/docforge, pull requests merged in 2021-11, with the labels that each got.

#239 Fix Golint issues
  cmd/app/cmd.go
  cmd/app/completion.go
  cmd/app/factory.go
  cmd/configuration/configuration.go
  cmd/configuration/types_configuration.go
  pkg/api/nodes.go
  pkg/api/parser.go
  pkg/git/git.go
  pkg/git/types.go
  pkg/hugo/fswriter.go
  pkg/jobs/jobs.go
  pkg/mock/git/git.go
  pkg/processors/document.go
  pkg/reactor/content_processor.go
  pkg/reactor/document_worker.go
  pkg/reactor/downloader.go
  pkg/reactor/github_info.go
  pkg/reactor/manifest_resolver.go
  pkg/reactor/validator.go
  pkg/reactor/validator_test.go
  pkg/resourcehandlers/fs/fs.go
  pkg/resourcehandlers/git/git_resource_handler.go
  pkg/resourcehandlers/git/git_resource_handler_test.go
  pkg/resourcehandlers/git/repository.go
  pkg/resourcehandlers/github/github_resource_handler.go
  pkg/resourcehandlers/github/github_utils.go
  pkg/resourcehandlers/github/gitinfo.go
  pkg/resourcehandlers/github/gitinfo_test.go
  pkg/resourcehandlers/github/resource_locator_cache.go
  pkg/util/httpclient/client.go
Labels: needs/ok-to-test, needs/review, size/m

#237 config feature
  cmd/app/cmd.go
  cmd/app/factory.go
  cmd/configuration/types_configuration.go
  pkg/api/parser.go
  pkg/api/parser_test.go
  pkg/resourcehandlers/fs/fs.go
  pkg/resourcehandlers/git/git_resource_handler.go
  pkg/resourcehandlers/git/git_resource_handler_test.go
  pkg/resourcehandlers/github/github_resource_handler.go
  pkg/resourcehandlers/github/github_resource_handler_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#238 Fix shell checks
  .ci/build
  .ci/check
  .ci/docs-gen
  .ci/docs-lint
  .ci/integration-test
  .ci/test
Labels: needs/ok-to-test, needs/review, size/m

#241 Delete redundant docs
  docs/dev-concurency.md
  docs/images/docforge-concurrency-pattern.svg
  docs/images/docforge-control-fwk.svg
  docs/images/docforge-err-multiplexing.svg
  pkg/api/parser.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#240 checkout fix
  pkg/resourcehandlers/git/repository.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#242 ginkgo version feature tests
  license_prefix.txt
  pkg/api/parser.go
  pkg/api/parserGinkgo_test.go
  pkg/api/parser_test.go
  pkg/git/git.go
  pkg/git/gitfakes/fake_git.go
  pkg/git/gitfakes/fake_repository.go
  pkg/git/gitfakes/fake_repository_worktree.go
  pkg/reactor/reactor.go
  pkg/reactor/reactorfakes/fake_download_scheduler.go
  pkg/reactor/reactorfakes/fake_git_hub_info.go
  pkg/reactor/reactorfakes/fake_reader.go
  pkg/reactor/reactorfakes/fake_validator.go
  pkg/resourcehandlers/fs/fs.go
  pkg/resourcehandlers/git/gitGinko_resource_handler_test.go
  pkg/resourcehandlers/git/git_resource_handler.go
  pkg/resourcehandlers/git/gitfakes/fake_file_info.go
  pkg/resourcehandlers/git/gitfakes/fake_file_reader.go
  pkg/resourcehandlers/github/githubGinko_resource_handler_test.go
  pkg/resourcehandlers/github/github_resource_handler.go
  pkg/resourcehandlers/github/github_resource_handler_test.go
  pkg/resourcehandlers/resource_handlers.go
  pkg/resourcehandlers/resourcehandlersfakes/fake_registry.go
  pkg/resourcehandlers/resourcehandlersfakes/fake_resource_handler.go
  pkg/util/httpclient/client.go
  pkg/util/httpclient/httpclientfakes/fake_client.go
  pkg/writers/writers.go
  pkg/writers/writersfakes/fake_writer.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xl

#247 fs removed
  cmd/app/factory.go
  cmd/app/manifest.go
  pkg/resourcehandlers/fs/fs.go
  pkg/resourcehandlers/fs/fs_test.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#246 Fix blogs duplication
  pkg/resourcehandlers/git/git_resource_handler.go
  pkg/resourcehandlers/github/github_resource_handler.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#249 [TEST PR] Add docforge manifest and check-manifest script
  .ci/check-manifest
  .ci/pipeline_definitions
  .docforge/manifest.yaml
  Makefile
Labels: needs/review, size/s

#250 oauth token is optional
  cmd/app/cmd.go
  cmd/app/factory.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#251 Oauth fix
  cmd/app/cmd.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#252 Do not use token in check-manifest
  .ci/check-manifest
Labels: needs/review

#253 Add API validations for the manifest
  cmd/app/cmd.go
  cmd/app/manifest.go
  pkg/api/parser.go
  pkg/api/parser_test.go
  pkg/api/types.go
  pkg/api/validate.go
  pkg/resourcehandlers/git/git_resource_handler.go
  pkg/resourcehandlers/github/github_resource_handler.go
Labels: kind/api-change, reviewed/lgtm, needs/ok-to-test, size/l

#255 Add more information in some errors
  pkg/processors/frontmatter.go
  pkg/reactor/document_worker.go
  pkg/reactor/reactor.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#248 git refactoring
  pkg/mock/git/git.go
  pkg/resourcehandlers/fs/testdata/d00/d02/f020.md
  pkg/resourcehandlers/fs/testdata/d00/f01.md
  pkg/resourcehandlers/fs/testdata/f00.md
  pkg/resourcehandlers/git/gitGinko_resource_handler_test.go
  pkg/resourcehandlers/git/git_resource_handler.go
  pkg/resourcehandlers/git/git_resource_handler_test.go
  pkg/resourcehandlers/git/gitinterface/git.go
  pkg/resourcehandlers/git/gitinterface/gitinterfacefakes/fake_git.go
  pkg/resourcehandlers/git/gitinterface/gitinterfacefakes/fake_repository.go
  pkg/resourcehandlers/git/gitinterface/gitinterfacefakes/fake_repository_worktree.go
  pkg/resourcehandlers/git/gitinterface/types.go
  pkg/resourcehandlers/git/repository.go
  pkg/resourcehandlers/github/gitinfo.go
  pkg/resourcehandlers/github/gitinfo_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xl
