Repository gardener/docforge, pull requests merged in 2022-08, with the labels that each got.

#282 Added flag descriptions in README
  README.md
Labels: reviewed/ok-to-test, needs/review, size/xs

#281 Change base image from alpine to distroless and update go version to 1.17.12
  .ci/pipeline_definitions
  Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#283 Vars and flags refactor
  .ci/integration-test
  cmd/app/cmd.go
  cmd/app/factory.go
  cmd/app/manifest.go
  integration-test/manifest.yaml
  pkg/api/parser.go
  pkg/api/parser_test.go
  pkg/resourcehandlers/git/git_resource_handler.go
  pkg/resourcehandlers/git/git_resource_handler_test.go
  pkg/resourcehandlers/github/github_resource_handler.go
  pkg/resourcehandlers/pg/pg.go
Labels: needs/ok-to-test, needs/review, size/m

#284 Documentation for refactored flags updated
  README.md
  diff_check.sh
  docs/cmd-ref/docforge.md
  docs/cmd-ref/docforge_completion.md
  docs/cmd-ref/docforge_gen-cmd-docs.md
  docs/cmd-ref/docforge_version.md
Labels: needs/ok-to-test, needs/review, size/s

#285 Todo cleanup
  cmd/app/cmd.go
  cmd/app/factory.go
  pkg/api/parser.go
  pkg/reactor/manifest_resolver.go
Labels: needs/ok-to-test, needs/review, size/s
