Repository gardener/docforge, pull requests merged in 2022-03, with the labels that each got.

#268 Parser reconfiguration
  .ci/integration-test
  cmd/app/cmd.go
  cmd/app/factory.go
  cmd/app/manifest.go
  pkg/api/parser.go
  pkg/api/parser_test.go
  pkg/reactor/content_processor_test.go
  pkg/resourcehandlers/git/git_resource_handler.go
  pkg/resourcehandlers/git/git_resource_handler_test.go
  pkg/resourcehandlers/github/github_resource_handler.go
  pkg/resourcehandlers/github/github_resource_handler_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xl

#270 Update check-manifest to support relative paths in manifest.yaml
  .ci/check-manifest
  .docforge/manifest.yaml
  cmd/app/cmd.go
  cmd/app/factory.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/s

#271 Avoid unexpected EOF errors, using cache for 'docs' repo folders
  pkg/reactor/reactor_test.go
  pkg/resourcehandlers/pg/pg.go
  pkg/util/resource_info.go
Labels: needs/ok-to-test, needs/review, size/s

#272 Remove redundant validation of relative links
  cmd/app/cmd.go
  pkg/reactor/content_processor.go
Labels: needs/ok-to-test, needs/review, size/xs

#273 Fix package & variable name collision
  pkg/resourcehandlers/pg/pg.go
Labels: needs/ok-to-test, needs/review, size/s

#275 Removes headers filter as Last-Modified does not reflect changes in subfolders
  cmd/app/factory.go
Labels: needs/ok-to-test, needs/review, size/xs

#276 Fix bug with the document titles
  pkg/reactor/content_processor.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#277 Update docs
  README.md
  cmd/app/cmd.go
  docs/cmd-ref/docforge.md
  docs/cmd-ref/docforge_gen-cmd-docs.md
  docs/consistency.md
  docs/manifest-ref.md
  docs/manifests.md
  docs/user-index.md
  docs/versions.md
  example/advanced/00.yaml
  example/advanced/01.yaml
  example/simple/00.yaml
  example/simple/01.yaml
  example/simple/02.yaml
  example/simple/03.yaml
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl
