Repository gardener/docforge, pull requests merged in 2023-12, with the labels that each got.

#304 Update testmachinery image location
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#307 Remove docs lint
  .ci/docs-lint
  .ci/pipeline_definitions
  Makefile
Labels: needs/ok-to-test, needs/review, size/xs

#306 Fix checks
  cmd/app/types.go
  integration-test/expected-metadata/mainTree/markdown-tests/file1.md.json
  pkg/manifest/export_test.go
  pkg/manifest/manifest.go
  pkg/manifest/manifest_types.go
  pkg/manifest/node.go
  pkg/manifest/options.go
  pkg/readers/link/resource_link.go
  pkg/readers/repositoryhosts/githubhttpcache/github_http_cache.go
  pkg/readers/repositoryhosts/registry.go
  pkg/readers/repositoryhosts/repositoryhostsfakes/local_filesystem_registry.go
  pkg/workers/document/document_worker.go
  pkg/workers/document/document_worker_test.go
  pkg/workers/document/frontmatter/frontmatter.go
  pkg/workers/document/frontmatter/frontmatter_test.go
  pkg/workers/document/job.go
  pkg/workers/downloader/downloader.go
  pkg/workers/downloader/job.go
  pkg/workers/githubinfo/github_info.go
  pkg/workers/githubinfo/github_info_test.go
  pkg/workers/githubinfo/job.go
  pkg/workers/linkresolver/link_resolving.go
  pkg/workers/linkresolver/link_resolving_test.go
  pkg/workers/linkvalidator/validator.go
  pkg/workers/taskqueue/taskqueue.go
  pkg/workers/taskqueue/taskqueue_collection.go
Labels: needs/ok-to-test, needs/review, size/m
