Repository gardener/docforge, pull requests merged in 2024-07, with the labels that each got.

#329 Minor changes
  cmd/app/exec.go
  cmd/app/flags.go
  cmd/app/types.go
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
  pkg/manifest/node.go
  pkg/manifest/tests/contents/docs/architecture/_index.md
  pkg/manifest/tests/contents/docs/architecture/concept.md
  pkg/manifest/tests/manifests/aliases.yaml
  pkg/manifest/tests/results/aliases.yaml
  pkg/registry/registry.go
  pkg/registry/repositoryhost/github_http_cache_test.go
  pkg/workers/document/document_worker.go
  pkg/workers/document/document_worker_test.go
  pkg/workers/document/job.go
  pkg/workers/linkvalidator/validator.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#330 Update `manifests.md`
  docs/manifests.md
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#332 Publish component descriptor and image to GAR instead of GCR
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#333 Migrate remaining GCR occurrences to GAR
  .ci/pipeline_definitions
  Makefile
  README.md
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#338 Fix: rm _path suffix from input names and env vars
  .ci/docs-gen
  .ci/pipeline_definitions
  .ci/update-release.py
Labels: needs/ok-to-test, needs/review, size/xs

#340 Remove check-manifest and docs-gen steps
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs
