Repository gardener/docforge, pull requests merged in 2025-02, with the labels that each got.

#384 Fix and refactor
  .ci/update-release.py
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/s

#383 Temporary disable e2e
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#385 Add a trailing slash only on hugo `.md` files
  pkg/link/link.go
  pkg/link/link_test.go
  pkg/manifest/node.go
  pkg/workers/linkresolver/link_resolving.go
Labels: needs/ok-to-test, needs/review, size/s

#386 Temporary remove e2e script
  .ci/e2e
Labels: needs/ok-to-test, needs/review, size/s

#387 NoOp e2e
  .ci/e2e
Labels: needs/ok-to-test, needs/review, size/xs

#388 fix regression from previous refactoring
  .ci/update-release.py
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#394 Add docforge_config.yaml for e2e test
  test/e2e/docforge_config.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#398 enable e2e in pipeline
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#395 task.sh: Add package of changes in commit message
  task.sh
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#399 Edit path to repo in diff.sh
  .ci/e2e
  test/e2e/diff.sh
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#397 Add testing goals
  test/README.md
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#396 Introduce `must.Succeed`
  pkg/link/link.go
  pkg/link/link_test.go
  pkg/must/assertions.go
  pkg/workers/linkresolver/link_resolving.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#400 Use `pkg/link` when building links for consistency
  pkg/link/link.go
  pkg/manifest/manifest.go
  pkg/manifest/node.go
  pkg/registry/repositoryhost/resource_url.go
  pkg/workers/document/document_worker.go
  pkg/workers/linkresolver/link_resolving.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#402 Introduce internal package
  pkg/internal/link/link.go
  pkg/internal/link/link_test.go
  pkg/internal/must/assertions.go
  pkg/manifest/manifest.go
  pkg/manifest/node.go
  pkg/registry/repositoryhost/resource_url.go
  pkg/workers/document/document_worker.go
  pkg/workers/linkresolver/link_resolving.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
